# Generated by Django 5.0.6 on 2024-06-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='correct_choice',
            field=models.BooleanField(default=False),
        ),
    ]
